shop/cart/urls.py
from django.urls import path
from .views import (
    add_to_cart_page, 
    display_cart_page, 
    payment_page,
    display_thanks_page,
    display_payment_respone_page,
    delete_cart_item_page,
    display_checkout_page)

app_name = 'cart'

urlpatterns = [
    path('user/cart', display_cart_page, name='display'),
    path('add/to/cart/<int:product_id>', add_to_cart_page, name='add_to_cart'),
    path('payment/cart/<int:cart_id>', payment_page, name='payment'),
    path('thanks-page', display_thanks_page, name='thanks_page'),
    path('response', display_payment_respone_page, name='response'),
    path('delete', delete_cart_item_page, name='delete'),
    path('checkout', display_checkout_page, name='checkout')
]

shop/product/urls.py
from django.urls import path
from .views import (
    all_products_page,
    add_product_page,
    detail_product_page,
    delete_product_page,
    update_product_page,
    add_category_page,
    delete_category_page,
    update_category_page,
    add_comment_to_product,
    add_comment_rate
)


app_name = 'product'
urlpatterns = [
    path('', all_products_page, name='home'),
    path('add', add_product_page, name='add'),
    path('details/<pk>', detail_product_page, name='details'),
    path('delete/<pk>', delete_product_page, name='delete'),
    path('update/<pk>', update_product_page, name='update'),
    path('category/add', add_category_page, name='add-category'),
    path('category/delete/<pk>', delete_category_page, name='delete-category'),
    path('category/update/<pk>', update_category_page, name='update-category'),
    path('comment/add/<product_pk>', add_comment_to_product, name='add-comment'),
    path('comment/<comment_pk>/add/rate/<product_id>', add_comment_rate, name='add-comment-rate')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('product.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard'))
]

shop/cart/models.py
from django.db import models
from django.urls import reverse

from product.models import Product
from account.models import CustomUser


# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    status = models.CharField(max_length=60, default='ACTIVE')
    creation_date = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    currency = models.CharField(max_length=3, default='PLN')


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField(default=1)

    def get_delete_url(self):
        return reverse('cart:delete')

shop/cart/views.py
import time
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Cart, CartItem
from product.models import Product
from .utils import create_payment_chk, send_bill_email


# Create your views here.
def add_to_cart_page(request, product_id):
    user_cart, new_user_cart = Cart.objects.get_or_create(user=request.user, status='ACTIVE')
    product = Product.objects.get(pk=product_id)

    if user_cart:
        # Increasing amount of product
        exist = CartItem.objects.filter(cart_id=user_cart.id, product_id=product.id).first()
         
        if exist:
            new_cart_item = exist
            new_cart_item.amount += 1
        else:
            new_cart_item = CartItem(cart=user_cart, product=product)
    else:
        new_cart_item = CartItem(cart=new_user_cart, product=product)

    new_cart_item.save()

    return redirect('product:home')

def display_cart_page(request):
    SHIPPING = 10
    # TODO
    # Change this approach of taking products to left join test this solution
    user_cart = Cart.objects.get(user=request.user, status='ACTIVE')
    cart_items = CartItem.objects.select_related('product').filter(cart=user_cart)
    print(cart_items.query)
    products = []
    total_price = 0

    for cart_item in cart_items:
        products.append(cart_item)
        total_price += cart_item.product.price * cart_item.amount
        
    context = {
        'cart_items': products,
        'cart': user_cart,
        'total_price': total_price,
        'currency': 'zł',
        'shipping': SHIPPING,
        'total_price_with_shipping': total_price + SHIPPING
    }
    
    return render(request, 'cart/display.html', context=context)

def payment_page(request, cart_id):
    SHIPPING = 10
    user_cart = Cart.objects.get(id=cart_id)
    cart_items = CartItem.objects.filter(cart=user_cart)
    amount = 0
    currency = user_cart.currency

    for cart_item in cart_items:
        product = Product.objects.get(pk=cart_item.product_id)
        amount += (cart_item.amount * product.price)

    dotpay_id = '742805'  # TODO hide in cofngi
    amount = str(round(amount + SHIPPING, 2))
    description = 'Test'
    type = '0'
    url = f'http://340b-87-239-222-251.ngrok.io{reverse("cart:thanks_page")}'
    urlc = 'http://340b-87-239-222-251.ngrok.io/cart/response'
    payment_data = {
        'id': dotpay_id,
        'amount': amount,
        'currency': currency,
        'description': description,
        'type': type,
        'url': url,
        'urlc': urlc
    }
    test_env = 'https://ssl.dotpay.pl/test_payment/'
    chk = create_payment_chk(payment_data)
    
    payment_url = f'{test_env}?id={dotpay_id}&amount={amount}&currency={currency}&description={description}&type={type}&url={url}&urlc={urlc}&chk={chk}'
    request.session['card_id'] = cart_id

    return redirect(payment_url)


def delete_cart_item_page(request, cart_item_id):
    pass

@csrf_exempt
def display_thanks_page(request):
    status = request.GET.get('status', 'none')
    
    context = {
        'status': status
    }

    return render(request, 'cart/thanks_page.html', context=context)


@csrf_exempt
def display_payment_respone_page(request):
    print(request.POST)
    print(f'Get response from payment in urlc, status: {request.POST["operation_status"]}')

    if request.POST['operation_status'] == 'completed':
        email = request.POST['email']
        amount = request.POST['operation_original_amount']
        card_id = request.POST['operation_number']
        send_bill_email(email, card_id, amount)

    return HttpResponse('OK')

def display_checkout_page(request):
    return render(request, 'cart/checkout.html', context={})

shop/cart/templates/cart/checkout.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-lg-8 col-12">
            <div>
                <h2>Fill you personal data</h2>
                <form method="post" action="#">
                    <div class="row g-3">
                        <div class="col-md-6">
                          <label for="inputName" class="form-label">First Name</label>
                          <input type="text" class="form-control" id="inputName">
                        </div>
                        <div class="col-md-6">
                          <label for="inputLastName" class="form-label">Last Name</label>
                          <input type="text" class="form-control" id="inputLastName">
                        </div>
                        <div class="col-12">
                          <label for="inputAddress" class="form-label">Address</label>
                          <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
                        </div>
                        <div class="col-12">
                          <label for="inputAddress2" class="form-label">Address 2</label>
                          <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
                        </div>
                        <div class="col-md-6">
                          <label for="inputCity" class="form-label">City</label>
                          <input type="text" class="form-control" id="inputCity">
                        </div>
                        <div class="col-md-4">
                          <label for="inputState" class="form-label">State</label>
                          <select id="inputState" class="form-select">
                            <option selected>Choose...</option>
                            <option>...</option>
                          </select>
                        </div>
                        <div class="col-md-2">
                          <label for="inputPostCode" class="form-label">Postal Code</label>
                          <input type="text" class="form-control" id="inputPostCode">
                        </div>
                      </div>
                </form>
            </div>
        </div>
        <div class="col-lg-4 col-12 mt-3 mt-lg-0">
            <div class="d-flex flex-column">
                <div>
                    <h3>Cart total</h3>
                    <div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex flex-row justify-content-between border-0">
                                Cart Subtotal <span class="d-inline">$$$</span>
                            </li>
                            <li  class="list-group-item d-flex flex-row justify-content-between">
                                Shipping <span>$$$</span>
                            </li>
                            <li class="list-group-item d-flex flex-row justify-content-between border-0">
                                You Pay <span>$$$</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="mt-3">
                    <h3>Payments</h3>
                    <div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex flex-row justify-content-between border-0">
                                Blick
                            </li>
                            <li  class="list-group-item d-flex flex-row justify-content-between">
                                MBank
                            </li>
                            <li class="list-group-item d-flex flex-row justify-content-between border-0">
                                PKO BP
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="mt-auto d-flex flex-row justify-content-center">
                    <button type="submit" class="btn btn-primary w-100">Buy</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

shop/cart/templates/cart/display.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>PRODUCT</th>
                            <th>NAME</th>
                            <th class="text-center">PRICE</th>
                            <th class="text-center">QUANTITY</th>
                            <th class="text-center">CATEGORY</th>
                            <th class="text-center"><i class="bi bi-trash"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <img src="http://dummyimage.com/70x50" alt="product-img">
                                </td>
                                <td>
                                    <p class="fs-5 fw-bolder">{{ cart_item.product.name }}</p>
                                </td>
                                <td>
                                    <p>{{ cart_item.product.price }}</p>
                                </td>
                                <td>
                                    <p>{{ cart_item.amount }}</p>
                                </td>
                                <td>
                                    <p>{{ cart_item.product.category }}</p>
                                </td>
                                <td class="text-center">
                                    <a class="link-dark" href="{{ cart_item.get_delete_url }}"><i class="bi bi-trash"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 col-md-5 col-12">
        </div>
        <div class="col-lg-4 col-md-7 col-12">
            <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex flex-row justify-content-between border-0">
                    Cart Subtotal <span class="d-inline">{{ total_price }} {{ currency }}</span>
                </li>
                <li  class="list-group-item d-flex flex-row justify-content-between">
                    Shipping <span>{{ shipping }} {{ currency }}</span>
                </li>
                <li class="list-group-item d-flex flex-row justify-content-between border-0">
                    You Pay <span>{{ total_price_with_shipping }} {{ currency }}</span>
                </li>
            </ul>
            <div class="d-flex flex-column">
                <a href="{% url 'cart:payment' cart.id %}" class="btn btn-primary">CHECKOUT</a>
                <a href="#" class="btn btn-primary mt-2">CONTINUE SHOPPING</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

shop/cart/templates/cart/payment.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
</head>

<body>
    <!-----------------------------
  
    Górna część strony
  
  ------------------------------------->

    <!---  copy  start--->
    <style>
        div.dotpay_form_donation {
            font-family: sans-serif;
            text-align: center;
        }


        div.dp_temat {
            font-size: 1.5em;
            font-style: inherit;
            font-weight: bold;
            color: #334242;
        }

        input#dp_def_amount {
            border: 1px solid #bbb;
            border-radius: 3px;
            height: 50px;
            font-size: 1.3em;
            background: #dae6ff;
            text-align: center;
            font-weight: 500;
            cursor: pointer;
        }

        input#dp_kwota {
            border: 1px solid #bbb;
            border-radius: 3px;
            font-size: 1.2em;
            background: #f8f6fb;
            text-align: center;

        }

        input#dp_other_amount {
            font-size: 1em;
            background: #daedff;
            border: 1px solid #bbb;
            border-radius: 3px;
            padding: 5px;
            text-align: center;
            cursor: pointer;
        }

        button#dp_buttomDarowizna {
            font-size: 1.3em;
            background: #ae3131;
            border: 1px solid #bbb;
            border-radius: 3px;
            padding: 5px;
            text-align: center;
            cursor: pointer;
            color: #f3f0ed;
            letter-spacing: 0.1em;
        }

        table.tbl_center {
            margin-left: auto;
            margin-right: auto;
        }
    </style>

    <!-- poniżej wpisz prawdiłową ścieżkę do jquery -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-3.5.1.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#dp_buttomDarowizna").click(function () {
                if ($('#dp_kwota').val().trim() === '') {
                    $("#dp_kwota_alert").text("Proszę wybrać lub wprowadzić kwotę darowizny.").show();
                    $('#dp_kwota_alert').css("display", "inline").fadeOut(5000);
                    return false;
                }
            });
        });
    </script>

    <div class="dotpay_form_donation">
        <form action="https://ssl.dotpay.pl/test_payment/" method="post" target="_parent">
            <div class="dp_temat">Wybierz kwotę darowizny</div>
            <p>
                <input type="button" id="dp_def_amount"
                    onClick="$('#dp_kwota').val('10'); $('#dp_kwota').prop('readonly', true);$('#dp_kwota').attr('style','color:blue');$('#dp_other_amount_txt').html('Wybrana Kwota')"
                    value="10.00 zł" />
                <input type="button" id="dp_def_amount"
                    onClick="$('#dp_kwota').val('20'); $('#dp_kwota').prop('readonly', true);$('#dp_kwota').attr('style','color:blue');$('#dp_other_amount_txt').html('Wybrana Kwota')"
                    value="20.00 zł" />
                <input type="button" id="dp_def_amount"
                    onClick="$('#dp_kwota').val('50'); $('#dp_kwota').prop('readonly', true);$('#dp_kwota').attr('style','color:blue');$('#dp_other_amount_txt').html('Wybrana Kwota')"
                    value="50.00 zł" />
                <input type="hidden" name="type" value="0" />
                <input type="hidden" name="currency" value="PLN" />

                <table class="tbl_center">
                    <tr>
                        <td>
                            <br><input type="button" id="dp_other_amount"
                                onClick="$('#dp_kwota').prop('readonly', false);$('#dp_kwota').attr('style','color:brown');$('#dp_other_amount_txt').html('<span style=\'color:brown\'>Wprowadź kwotę</span>')"
                                value="Inna kwota" />
                        </td>
                        <td>
                            <br><span id="dp_other_amount_txt">Wybrana Kwota</span>:
                            <input type="text" name="amount" id="dp_kwota" readonly
                                pattern="^([1-9])((\.\d{1,2})?)$|^((?!0)(\d){1,5})((\.\d{1,2})?)$|^(1(\d{5})(.\d{1,2})?)$|^(200000(.[0]{1,2})?)$"
                                placeholder="np. 100" maxlength="9" size="9"
                                title="Kwota powinna zawierać się w przedziale 1 - 200000 PLN. Dozwolony format to np: 100 lub 152.43"
                                oninput="this.value = this.value.replace(/[^0-9\.]/g, ''); this.value = this.value.replace(/(\..*)\./g, '$1');" />
                            PLN
                            <br />
                        </td>
                    </tr>
                </table>

                <!--------------------------------- KONFIGURACJA --------------------------------------->

                <!---- zamiast 000000 nalezy podstawic numer ID w Dotpay -->
                <input type="hidden" name="id" value="742805" />
                <!--- Tytuł transakcji --->
                <input type="hidden" name="description" value="Testowa płatność" />
                <!--- Ardes URL powrotu --->
                <input type="hidden" name="url" value="http://www.example.com" />
                <!-- Tekst przycisku powrotu do sklepu --->
                <input type="hidden" name="buttontext" id="buttontext" value="Powrót do sprzedawcy" />
            </p>

            <!--------------------------------- KONIEC KONFIGURACJI --------------------------------------->

            <p><br><button class="dp_buttomDarowizna" id="dp_buttomDarowizna">Wpłać darowiznę</button></p>
        </form>
        <div id="dp_kwota_alert" style="color:red;"></div>
    </div>

    <!---  copy  end--->

    <!-----------------------------
  
    Dolna część strony
  
  ------------------------------------->

<b>{{ res }}</b>

</body>

</html>

shop/cart/templates/cart/thanks_page.html


<h3>Thans for your shopping</h3>

<b>Response parameter "status": {{ status }}</b>

<h2><a href="{% url 'product:home' %}">Back to home site</a></h2>