shop/cart/urls.py
from django.urls import path
from .views import (
    add_to_cart_page, 
    display_cart_page, 
    payment_page,
    display_thanks_page,
    display_payment_respone_page,
    delete_cart_item_page,
    display_checkout_page)

app_name = 'cart'

urlpatterns = [
    path('user/cart', display_cart_page, name='display'),
    path('add/to/cart/<int:product_id>', add_to_cart_page, name='add_to_cart'),
    path('payment/cart/<int:cart_id>', payment_page, name='payment'),
    path('thanks-page', display_thanks_page, name='thanks_page'),
    path('response', display_payment_respone_page, name='response'),
    path('delete', delete_cart_item_page, name='delete'),
    path('checkout', display_checkout_page, name='checkout')
]

shop/product/urls.py
from django.urls import path
from .views import (
    all_products_page,
    add_product_page,
    detail_product_page,
    delete_product_page,
    update_product_page,
    add_category_page,
    delete_category_page,
    update_category_page,
    add_comment_to_product,
    add_comment_rate
)


app_name = 'product'
urlpatterns = [
    path('', all_products_page, name='home'),
    path('add', add_product_page, name='add'),
    path('details/<pk>', detail_product_page, name='details'),
    path('delete/<pk>', delete_product_page, name='delete'),
    path('update/<pk>', update_product_page, name='update'),
    path('category/add', add_category_page, name='add-category'),
    path('category/delete/<pk>', delete_category_page, name='delete-category'),
    path('category/update/<pk>', update_category_page, name='update-category'),
    path('comment/add/<product_pk>', add_comment_to_product, name='add-comment'),
    path('comment/<comment_pk>/add/rate/<product_id>', add_comment_rate, name='add-comment-rate')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('product.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard'))
]

shop/product/models.py
from enum import Enum
from django.db import models
from django.urls import reverse
from account.models import CustomUser

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name

    def get_delete_url(self):
        return reverse('product:delete-category', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('product:update-category', kwargs={'pk': self.pk})

class Product(models.Model):
    name = models.CharField(max_length=254)    
    price = models.FloatField(default=0)
    description = models.TextField(max_length=1000)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:details', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('product:delete', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('product:update', kwargs={'pk': self.pk})
        

class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    body = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    vote_plus = models.IntegerField(default=0)
    vote_minus = models.IntegerField(default=0)
    bought = models.BooleanField(default=False)


class CommentRate(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    vote = models.SmallIntegerField()


class VoteType(Enum):
    minus = 0
    plus = 1

shop/product/forms.py
from dataclasses import field
from django.forms import ModelForm
from .models import Product, Category, Comment


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

shop/product/views.py
from django.http import HttpResponse, JsonResponse, response
from django.shortcuts import redirect, render, get_object_or_404
from django.urls.base import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Comment, Product, Category, CommentRate, VoteType
from .forms import CategoryForm, ProductForm, CommentForm


# Product
def all_products_page(request):
    products = Product.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(products, per_page=12)

    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    categories = Category.objects.all()

    context = {
        'products': page_obj,
        'categories': categories,
    }
    
    return render(request, 'product/home.html', context)

def add_product_page(request): 
    if request.method == 'POST':
        form = ProductForm(request.POST)

        if form.is_valid():
            form.save()

            return render(request, 'product/add.html', {})
        else:
            return render(request, 'product/add.html', {})
    else:
        form = ProductForm()
        context = {
            'form': form
        }

        return render(request, 'product/add.html', context)


def detail_product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    comments_query = Comment.objects.filter(product_id=pk)
    user_comment = Comment.objects.filter(user_id=request.user.id, product_id=pk)

    comments = comments_query if comments_query else []
    # can_comment = False if comments else True
    can_comment =  True
    comment_form = CommentForm

    context = {
        'product': product,
        'comments': comments,
        'can_comment': can_comment,
        'form': comment_form
    }

    return render(request, 'product/details.html', context)


def delete_product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)

    product.delete()

    return redirect('product:home')

def update_product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        updated_product = ProductForm(request.POST or None, instance=product)

        if updated_product.is_valid():
            updated_product.save(commit=False)
            product.save()

            return redirect('product:home')
        else:
            return HttpResponse(updated_product.errors)
    else:
        form = ProductForm(request.POST or None, instance=product)
        context = {
            'form': form
        }

    return render(request, 'product/update.html', context)

def add_category_page(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('product:home')
        else:
            return render(request, 'category/add.html', {})
    else:
        form = CategoryForm()
        context = {
            'form': form
        }

        return render(request, 'category/add.html', context)


def delete_category_page(request, pk):
    category = get_object_or_404(Category, pk=pk)

    category.delete()
    
    return redirect('product:home')

def update_category_page(request, pk):
    category = get_object_or_404(Category, pk=pk)

    if request.method == 'POST':
        updated_category = CategoryForm(request.POST or None, instance=category)

        if updated_category.is_valid():
            updated_category.save(commit=False)
            category.save()

            return redirect('product:home')
        else:
            return redirect('product:home')
    else:
        form = CategoryForm(request.POST or None, instance=category)
        context = {
            'form': form
        }

        return render(request, 'category/update.html', context)


def add_comment_to_product(request, product_pk):
    # TODO use form and add values before insert
    if request.method == 'POST':
        new_comment = Comment()
        new_comment.body = request.POST['body']
        new_comment.user_id = request.user.id
        new_comment.product_id = product_pk

        new_comment.save()

        response = {
            'add_comment': True
        }
        
        return JsonResponse(response)
    else:
        return HttpResponse('Not POST request')


def add_comment_rate(request, product_pk, comment_pk):
    if request.method == 'POST':
        vote = request.POST['vote']
        new_comment_rate = CommentRate()
        new_comment_rate.user_id = request.user.id
        new_comment_rate.product_id = product_pk
        new_comment_rate.vote = vote

        new_comment_rate.save()

        # change comment value
        comment = Comment.objects.get(pk=comment_pk)

        if vote == VoteType.plus:
            comment.vote_plus += 1
        elif vote == VoteType.minus and comment.vote_minus >= 0:
            comment.vote_minus -= 1
        else:
            return JsonResponse({
                'add_rate': False,
                'message': 'Invalid vote type!'
            })

        comment.save()

        response = {
            'add_rate': True,
            'message': 'Rate added correctly.',
            'vote_plus': comment.vote_plus,
            'vote_minus': comment.vote_minus
        }

        return JsonResponse(response)
    else:
        return HttpResponse('Not POST request!')
        

shop/product/templates/product/add.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add product</button>
</form>
{% endblock content %}

shop/product/templates/product/details.html
{% extends "base.html" %}
{% block content %}
<style>
    .comment_block {
        width: 100%;
        border: 1px dashed black;
    }

    .comment_body {
        width: 85%;
        float: left;
    }

    .comment_rate {
        width: 15%;
        float: left;
    }

    .comment_rate a {
        text-decoration: none;
        font-size: 24px;
        font-weight: bolder;
    }
</style>



<h3>{{ product.name }}</h3>

<p>{{ product.price }}</p>
<p>{{ product.description }}</p>
<p>{{ product.category }}</p>

<hr>
<h4>Comments section</h4>
{% for user_comment in comments %}
    <div class="comment_block">
        <div class="comment_body"> 
            <input id="comment_id" type="hidden" value="{{ user_comment.id }}">
            <b>{{ user_comment.id }}</b>
            <p>{{ user_comment.body }}</p>
        </div>
        <div class="comment_rate">
            <p>votes plus: {{ user_comment.vote_plus }}<button class="rate_btn" type="button" value="1">+</button></p>
            <p>votes minus: {{ user_comment.vote_minus }}<button class="rate_btn" type="button" value="0">-</button></p>
        </div>
        <div style="clear: both;"></div>
    </div>
{% endfor %}

<hr>


{% if can_comment %}
<form method="POST" action="" id="comment-add-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add comment</button>
</form>
{% else %}
<p>Already commented this product :)</p>
{% endif %}


<script>
    // Add comment rate
    // get one of many buttons for plus or minus
    document.querySelectorAll('.rate_btn').forEach(item => {
        item.addEventListener('click', addCommentRate);
    });

    function addCommentRate(e) {
        let req = new XMLHttpRequest();

        req.onreadystatechange = () => {

        }

        req.open('POST', "{% url 'product:add-comment-rate' product.id %}", true);
        req.send(this.value)
    }

    /* Add comment */
    let commentForm = document.getElementById('comment-add-form');
    commentForm.addEventListener('submit', (e) => {
        console.log(commentForm.method);
        

        let req = new XMLHttpRequest();

        req.onreadystatechange = () => {
            if (req.readyState === XMLHttpRequest.DONE) {
                if (req.status === 200) {
                    console.log('Correct status!');
                    commentForm.replaceChild = '<p>You already commented!</p>'
                } else {
                    console.log(`Invalid status, code: {req.status}`);
                }
            } else {
                console.log('Request not ready yey.');
            }
        }

        if (commentForm.method.toUpperCase() === 'POST') {
            req.open('POST', "{% url 'product:add-comment' product.id %}", true);
            req.send(new FormData(commentForm));
        }
    })
</script>
{% endblock content %}

shop/product/templates/product/home.html
{% extends "base.html" %}

{% block content %}
<div class="mb-3">
<div class="row">
    <div class="col-lg-3 col-md-4 col-12 mt-3 bg-dark">
        <div class="d-flex flex-column bg-light mt-3 p-3">
            <div class="text-center">
                <h3>Categories</h3>
                <hr>
            </div>
            <div class="list-group">
                {% for category in categories %}
                    <a href="#" class="list-group-item list-group-item-action">{{ category.name }}</a>
                {% endfor %}
              </div>
        </div>

        <div class="d-flex flex-column bg-light mt-3 p-3 mb-3">
            <div class="text-center">
                <h3>Price</h3>
                <hr>
            </div>
            <input type="range" class="form-range" min="0" max="5" step="0.5" id="customRange3">
        </div>
    </div>
    <div class="col-lg-9 col-md-8 col-12"> 
        <div class="row">
            {% for product in products %}
                <div class="col-lg-4 col-md-6 col-12 mt-3">
                    <div class="card">
                        <div>
                            <img class="card-img-top" src="http://dummyimage.com/140x120" alt="Product img" style="width: 100%; height: 100%;">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text" style="font-size: 12px;">{{ product.price }}</p>
                            <a class="btn btn-primary" href="{% url 'cart:add_to_cart' product.id %}">Add to cart</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col d-flex justify-content-center">
                <nav class="mt-3" aria-label="Search product list">
                    <ul class="pagination">
                        {% if products.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        {% endif %}
                        
                        {% for i in products.paginator.page_range %}
                            {% if products.number == i %}
                                <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor%}

                        {% if products.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        {% endif%}
                        
                    </ul>
                  </nav>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

shop/product/templates/product/update.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update product</button>
</form>
{% endblock content %}