shop/account/urls.py
from django.urls import path
from .views import (
    register_page,
    login_page,
    logout_page,
    confirm_email_page,
    login_oauth_page,
    auth_page,
    login_oauth_user_page,
    display_account_page)


app_name = 'account'
urlpatterns = [
    path('register', register_page, name='register'),
    path('login', login_page, name='login'),
    path('logout', logout_page, name='logout'),
    path('confirm/email/<email>/hash/<hash>', confirm_email_page, name='confirm_email'),
    path('login/auth', login_oauth_page, name='login-auth'),
    path('login/auth/o', auth_page, name='auth'),
    path('login/auth/user', login_oauth_user_page, name='login-oauth-user'),
    path('account', display_account_page, name='account'),
]

shop/cart/urls.py
from django.urls import path
from .views import (
    add_to_cart_page, 
    display_cart_page, 
    payment_page,
    display_thanks_page,
    display_payment_respone_page,
    delete_cart_item_page,
    display_checkout_page)

app_name = 'cart'

urlpatterns = [
    path('user/cart', display_cart_page, name='display'),
    path('add/to/cart/<int:product_id>', add_to_cart_page, name='add_to_cart'),
    path('payment/cart/<int:cart_id>', payment_page, name='payment'),
    path('thanks-page', display_thanks_page, name='thanks_page'),
    path('response', display_payment_respone_page, name='response'),
    path('delete', delete_cart_item_page, name='delete'),
    path('checkout', display_checkout_page, name='checkout')
]

shop/product/urls.py
from django.urls import path
from .views import (
    all_products_page,
    add_product_page,
    detail_product_page,
    delete_product_page,
    update_product_page,
    add_category_page,
    delete_category_page,
    update_category_page,
    add_comment_to_product,
    add_comment_rate
)


app_name = 'product'
urlpatterns = [
    path('', all_products_page, name='home'),
    path('add', add_product_page, name='add'),
    path('details/<pk>', detail_product_page, name='details'),
    path('delete/<pk>', delete_product_page, name='delete'),
    path('update/<pk>', update_product_page, name='update'),
    path('category/add', add_category_page, name='add-category'),
    path('category/delete/<pk>', delete_category_page, name='delete-category'),
    path('category/update/<pk>', update_category_page, name='update-category'),
    path('comment/add/<product_pk>', add_comment_to_product, name='add-comment'),
    path('comment/<comment_pk>/add/rate/<product_id>', add_comment_rate, name='add-comment-rate')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('product.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard'))
]

shop/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>One Shop</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="{% static 'shop/widgets.css' %}">
</head>
<body class="d-flex flex-column min-vh-100">
    {% include "base_nav.html" %}

    {% include "base_alert.html" %}

    <div class="container mt-auto">
        {% block content %}
            <p>Test</p>
        {% endblock content %}
    </div>

    {% include "base_footer.html" %}
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/base_alert.html
<div class="container">
{% if messages %}
  {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      <div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div>
          {{ message }}
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
      <div class="alert alert-warning d-flex align-items-center alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div>
          {{ message }}
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
      <div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
        <div>
          {{ message }}
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      <div class="alert alert-primary d-flex align-items-center alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
        <div>
          {{ message }}
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}
</div>

shop/templates/base_content.html
{% extends "base.html" %}
{% block contet %}

{% endblock %}

shop/templates/base_footer.html
<style>
    .email_input input {
        width: 70%;
    }

    .social_media ul {
        text-align: center;
    }

    .social_media ul li a {
        font-size: 24px;
        color: black;
        text-decoration: none;
    }

    .social_media ul li a:hover {
        color: #5b8c5a;
    }

    .social_media ul li a i{
        padding: 0 0.5vw;
    }

    .social_media ul li:first-child::after {
        content: "";
        margin: 0;
    }
</style>

<footer class="bg-dark mt-3 mt-md-auto">
    <div class="container bg-dark text-light">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-12 mt-2 mt-lg-4">
                <div>
                    <p class="display-4 fw-bold">One Shop</p>
                    <p class="fs-6">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse in maximus tellus. 
                        Vestibulum euismod venenatis augue, non eleifend quam interdum non. 
                    </p>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-12 mt-2 mt-lg-4">
                <div>
                    <h4>Join Our Newsletter Now</h4>
                    <p>Get E-mail updates about our latest special offers.</p>
                    
                    <form class="row row-cols-lg-auto g-3 align-items-center">
                        <div class="col-12">
                            <input type="text" name="newsletter" id="newsletter" class="form-control">
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">SUBSCRIBE</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div class="container-fluid bg-dark text-light mt-2">
            <div>
                <div class="mx-3 mx-lg-5">
                    <div class="row border-top">
                        <div class="col-12">
                            <p class="text-center mt-3">Copyright &copy; Zavioer 2022</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>      
            

shop/templates/base_header.html
<style>
    ul {
        padding: 0;
        margin: 0;
    }

    ul li {
        display: inline-block;
        margin-right: 10px;
    }

    ul li:nth-child(1)::after {
        content: "|";
        margin-left: 10px;
    }

    .header_second ul {
        float: right;
    }

    .header_second ul li:nth-child(1)::after {
        content: "|";
        margin-left: 10px;
    }

    .header_second ul li:nth-child(2)::after {
        content: "|";
        margin-left: 10px;
    }

    .header_second ul li:nth-child(1) i {
        padding: 0 10px;
    }

</style>
<div class="col">
    <ul>
        <li>
            <i class="bi bi-envelope"></i>
            no-reply@shop.com
        </li>
        <li>
            Free Shippinh for all Order of 120 ZŁ
        </li>
    </ul>
</div>
<div class="col header_second">
    <ul>
        <li>
            <i class="bi bi-meta"></i>
            <i class="bi bi-twitter"></i>
            <i class="bi bi-linkedin"></i>
        </li>
        <li>
            <i class="bi bi-chevron-double-right"></i>
            Polish
        </li>
        <li>
            <i class="bi bi-person-fill"></i>
            {% if user.is_authenticated %}
                <a href="{% url 'account:logout' %}">Log out</a>
            {% else %}
                <a href="{% url 'account:login' %}">Login</a>
            {% endif %}
        </li>
    </ul>
</div>

shop/templates/base_nav.html


<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">One Shop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body bg-dark">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'cart:display' %}">MY CART</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'product:home' %}">PRODUCTS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">CONTACT</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto ">
                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href="#"><i class="bi bi-cart3 me-1"></i></a>
                </li>
                <li class="nav-item">
                  {% if user.is_authenticated %}
                    <a class="nav-link mx-2 text-uppercase" href="{% url 'account:account' %}"><i class="bi bi-person-fill me-1"></i></a>
                  {% else %}
                    <a class="nav-link mx-2 text-uppercase" href="{% url 'account:login' %}"><i class="bi bi-person-fill me-1"></i></a>
                  {% endif %}
                </li>
            </ul>
        </div>
      </div>
    </div>
  </nav>