shop/cart/urls.py
from django.urls import path
from .views import (
    add_to_cart_page, 
    display_cart_page, 
    payment_page,
    display_thanks_page,
    display_payment_respone_page,
    delete_cart_item_page,
    display_checkout_page)

app_name = 'cart'

urlpatterns = [
    path('user/cart', display_cart_page, name='display'),
    path('add/to/cart/<int:product_id>', add_to_cart_page, name='add_to_cart'),
    path('payment/cart/<int:cart_id>', payment_page, name='payment'),
    path('thanks-page', display_thanks_page, name='thanks_page'),
    path('response', display_payment_respone_page, name='response'),
    path('delete', delete_cart_item_page, name='delete'),
    path('checkout', display_checkout_page, name='checkout')
]

shop/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.display_panel_page, name='panel'),
    path('product', views.product_panel_page, name='panel-product'),
    path('category', views.category_panel_page, name='panel-category'),
]

shop/product/urls.py
from django.urls import path
from .views import (
    all_products_page,
    add_product_page,
    detail_product_page,
    delete_product_page,
    update_product_page,
    add_category_page,
    delete_category_page,
    update_category_page,
    add_comment_to_product,
    add_comment_rate
)


app_name = 'product'
urlpatterns = [
    path('', all_products_page, name='home'),
    path('add', add_product_page, name='add'),
    path('details/<pk>', detail_product_page, name='details'),
    path('delete/<pk>', delete_product_page, name='delete'),
    path('update/<pk>', update_product_page, name='update'),
    path('category/add', add_category_page, name='add-category'),
    path('category/delete/<pk>', delete_category_page, name='delete-category'),
    path('category/update/<pk>', update_category_page, name='update-category'),
    path('comment/add/<product_pk>', add_comment_to_product, name='add-comment'),
    path('comment/<comment_pk>/add/rate/<product_id>', add_comment_rate, name='add-comment-rate')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('product.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard'))
]

shop/dashboard/models.py
from django.db import models

# Create your models here.

class VwMostSoldProduct(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField() 
    amount = models.IntegerField()
    total = models.FloatField()

    class Meta:
        managed = False
        db_table = 'vw_most_sold_product'

shop/dashboard/views.py
from django.shortcuts import render
from .models import VwMostSoldProduct

from product.models import Product, Category

from plotly.offline import plot
from plotly.graph_objects import Bar


# Create your views here.
def display_panel_page(request):
    objects = VwMostSoldProduct.objects.all().values()
    limited = objects[:10]
    x = []
    y = []

    for obj in limited:
        x.append(obj['name'])
        y.append(obj['amount'])

    chart = plot([Bar(x=x, y=y,
                    name='test')],
            output_type='div')

    context = {
        'objects': objects,
        'chart': chart
    }
    return render(request, 'dashboard/panel.html', context)


def product_panel_page(request):
    products = Product.objects.all().order_by('id')

    context = {
        'products': products
    }
    return render(request, 'dashboard/product_panel.html', context)


def category_panel_page(request):
    categories = Category.objects.all().order_by('id')

    context = {
        'categories': categories
    }
    return render(request, 'dashboard/category_panel.html', context)

shop/dashboard/templates/dashboard/category_panel.html
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    {% for category in categories %}
        <tr>
            <td>{{ category.id }}</td>
            <td>{{ category.name }}</td>
            <td><a href="{{ category.get_update_url }}">Update</a></td>
            <td><a href="{{ category.get_delete_url }}">Delete</a></td>
        </tr>
    {% endfor %}
</table>

<hr />

<a href="{% url 'product:add-category' %}">Add new category</a>

shop/dashboard/templates/dashboard/panel.html
{% include 'nav.html' %}
<h3>Dashboard main panel</h3>

<!-- <nav>
    <a href=""></a>
</nav> -->

<table class="most_sold_product">
    <tr>
        <th>Product ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Amount</th>
        <th>Total sold</th>
    </tr>
    {% for product in objects %}
        <tr>
            <td>{{ product.id}}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.price }}</td>
            <td>{{ product.amount }}</td>
            <td>{{ product.total}}</td>
        </tr>
    {% endfor%}
</table>

{% autoescape off %}
{{ chart}}
{% endautoescape %}

shop/dashboard/templates/dashboard/product_panel.html
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Category</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    {% for product in products %}
        <tr>
            <td>{{ product.id }}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.price }}</td>
            <td>{{ product.description }}</td>
            <td>{{ product.category_id }}</td>
            <td><a href="{{ product.get_update_url }}">Update</a></td>
            <td><a href="{{ product.get_delete_url }}">Delete</a></td>
        </tr>
    {% endfor %}
</table>

<hr />

<a href="{% url 'product:add' %}">Add new product</a>